from core import CDPR #relative import of core
import time
import logging

#logging.basicConfig(level=logging.DEBUG)

print("Initialising")
cdpr = CDPR()
#quick test accel var
accel = 30
accel2 = 30

cdpr.release_ser()
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((-13, 4, 0), accel, relative=False)
cdpr.grab_ser()
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((13, 5, 2), accel, relative=False)
cdpr.goto((13, 3, 2), accel, relative=False)
cdpr.release_ser()
cdpr.goto((13, 5, 2), accel, relative=False)
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((-13, 4, 0), accel, relative=False)
cdpr.grab_ser()
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((13, 5, 4), accel, relative=False)
cdpr.goto((13, 3, 4), accel, relative=False)
cdpr.release_ser()
cdpr.goto((13, 5, 4), accel, relative=False)
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((-13, 4, 0), accel, relative=False)
cdpr.grab_ser()
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((15, 5, 2), accel, relative=False)
cdpr.goto((15, 3, 2), accel, relative=False)
cdpr.release_ser()
cdpr.goto((15, 5, 2), accel, relative=False)
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((-13, 4, 0), accel, relative=False)
cdpr.grab_ser()
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((15, 5, 4), accel, relative=False)
cdpr.goto((15, 3, 4), accel, relative=False)
cdpr.release_ser()
cdpr.goto((15, 5, 4), accel, relative=False)
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((-13, 4, 0), accel, relative=False)
cdpr.grab_ser()
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((13, 6, 2), accel, relative=False)
cdpr.goto((13, 4, 2), accel, relative=False)
cdpr.release_ser()
cdpr.goto((13, 6, 2), accel, relative=False)
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((-13, 4, 0), accel, relative=False)
cdpr.grab_ser()
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((13, 6, 4), accel, relative=False)
cdpr.goto((13, 4, 4), accel, relative=False)
cdpr.release_ser()
cdpr.goto((13, 6, 4), accel, relative=False)
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((-13, 4, 0), accel, relative=False)
cdpr.grab_ser()
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((15, 6, 2), accel, relative=False)
cdpr.goto((15, 4, 2), accel, relative=False)
cdpr.release_ser()
cdpr.goto((15, 6, 2), accel, relative=False)
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((-13, 4, 0), accel, relative=False)
cdpr.grab_ser()
cdpr.goto((-13, 6, 0), accel, relative=False)
cdpr.goto((15, 6, 4), accel, relative=False)
cdpr.goto((15, 4, 4), accel, relative=False)
cdpr.release_ser()
cdpr.goto((15, 6, 4), accel, relative=False)
cdpr.goto((0, 4, 0), accel, relative=False)


cdpr.shutdown()
print("Shutdown")